### ISSUE TITLE
Guides are pointed the wrong direction when using custom notes

### ISSUE THREAD

**Issue by Lunvrc** [Loloppe/BeatSaber_NoteCutGuide#1]
As the titles suggests, when using custom notes (i've tried all the different ones i have) the notes seem to just do a 90 degree turn to the left, the settings i change within the mods config makes no difference. 

i've attached this video to possibly explain it better. 

https://youtu.be/l7hMkdXYgxQ

**Comment by Loloppe** [comment]
It is as if the axis when using CustomNotes was mirrored or something like, I will try to fix that.

**Comment by Lunvrc** [comment]
Thanks a bunch

**Comment by Loloppe** [comment]
I added a variant plugin for CustomNotes, this simply turn off any kind of angle modification and dot note (all the guide are gonna be straight cut direction). The guide also doesn't scale properly with note size (you can use the config to fix this). If you wish to use a different note scale while keeping the angle setting, consider using BeatSaberPlus_NoteTweaker, this is what I've been using and it work fine (but can't have specific custom notes).

There's no easy way to fix the issue with CustomNotes I'm afraid. My algorithm got some pretty serious issue if CustomNotes is being used.
